### ISSUE TITLE
Server crash with Missile Form

### ISSUE THREAD

**Issue by elazullizard** [dkmk100/ArsOmega#13]
When casting a spell with Missile form, the game immediately crashes, throwing a NoSuchMethodError.

This error is reproducible in both singleplayer and multiplayer worlds.

Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'double com.hollingsworth.arsnouveau.api.spell.SpellStats.getAoeMultiplier()'
	at com.dkmk100.arsomega.glyphs.FormMissile.summonProjectiles(FormMissile.java:47) ~[arsomega-2.6.1.jar%2358!/:2.6.0] {re:classloading}
	at com.dkmk100.arsomega.glyphs.FormMissile.onCast(FormMissile.java:114) ~[arsomega-2.6.1.jar%2358!/:2.6.0] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.SpellResolver.onCast(SpellResolver.java:92) ~[ars_nouveau-1.18.2-2.4.2.jar%2356!/:2.4.2] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.ISpellCaster.castSpell(ISpellCaster.java:147) ~[ars_nouveau-1.18.2-2.4.2.jar%2356!/:2.4.2] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.ISpellCaster.castSpell(ISpellCaster.java:153) ~[ars_nouveau-1.18.2-2.4.2.jar%2356!/:2.4.2] {re:classloading}
	at com.hollingsworth.arsnouveau.common.items.SpellBook.m_7203_(SpellBook.java:86) ~[ars_nouveau-1.18.2-2.4.2.jar%2356!/:2.4.2] {re:classloading}

**Comment by dkmk100** [comment]
Updating ars will fix this, I'm using a new feature from the mod. Any version after 2.5.0 should work. 

I should have updated the mods.toml file so that forge would warn you about that, sorry.
